"""index feature created_at

Revision ID: c6c537177ba5
Revises: b45c3ac248b1
Create Date: 2026-08-06 17:30:28.712400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c537177ba5'
down_revision: Union[str, Sequence[str], None] = 'b45c3ac248b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_features_created_at'), 'features', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_features_created_at'), table_name='features')
    # ### end Alembic commands ###
